spring:
  datasource:
    url: jdbc:mysql://localhost:3306/student_registration?useSSL=false&serverTimezone=UTC
    username: servbyte
    password: servbyte

  jpa:
    hibernate:
      ddl-auto: update
